/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author maldad
 */
public class Pregunta extends javax.swing.JPanel {

    /**
     * Creates new form Pregunta
     */
    private String respuesta = "respuesta secreta";
    private String pregunta = "Escriba aquí su pregunta";
    private int reactivoCorrecto;
    public Pregunta() {
        initComponents();
        //esto es por default
        jLabel1.setText(pregunta);
        reactivoCorrecto = 1;
        jRadioButton1.setText(respuesta);
    }
    
    public void setReactivoCorrecto(int r){
        resetReactivos();
        if(r < 0){
            reactivoCorrecto = 1;
            ajustarReactivo(reactivoCorrecto);
        }
        if(r >= 1 || r <= 4){
            
            reactivoCorrecto = r;
            ajustarReactivo(reactivoCorrecto);
        }
    }
    
    public void setRespuesta(String r){
        respuesta = r;
        ajustarReactivo(reactivoCorrecto);
    }
    
    public void setPregunta(String p){
        pregunta = p;
        jLabel1.setText(pregunta);
    }
    
    public void ajustarReactivo(int r){
        switch(r){
            case(1): jRadioButton1.setText(respuesta);break;
            case(2): jRadioButton2.setText(respuesta);break;
            case(3): jRadioButton3.setText(respuesta);break;
            case(4): jRadioButton4.setText(respuesta);break;
        }
    }
    
    public void resetReactivos(){
        jRadioButton1.setText("Respuesta 1");
        jRadioButton2.setText("Respuesta 2");
        jRadioButton3.setText("Respuesta 3");
        jRadioButton4.setText("Respuesta 4");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        jLabel1.setText("1.- Escriba aquí su pregunta: ");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Respuesta 1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Respuesta 2");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Respuesta 3");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Respuesta 4");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton2))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton4)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        String r = jRadioButton1.getText();
        if(r.equals(respuesta)){
            System.out.println("¡Respuesta correcta!");
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        String r = jRadioButton2.getText();
        if(r.equals(respuesta)){
            System.out.println("¡Respuesta correcta!");
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        String r = jRadioButton3.getText();
        if(r.equals(respuesta)){
            System.out.println("¡Respuesta correcta!");
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        String r = jRadioButton4.getText();
        if(r.equals(respuesta)){
            System.out.println("¡Respuesta correcta!");
        }
    }//GEN-LAST:event_jRadioButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
}
