CREATE TABLE consulta(
    IDCONSULTA INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    PACIENTE INTEGER,
    CITA INTEGER,
    DIAGNOSTICO VARCHAR(30) NOT NULL,
    CONSTRAINT FKPACIENTE FOREIGN KEY (PACIENTE) REFERENCES PACIENTE(IDPACIENTE),
    CONSTRAINT FKIDCITA FOREIGN KEY (CITA) REFERENCES CITA(IDCITA)
    --         nombreFK             columnaLOcal      nombreTabla (columnaRefenciada)
)
