/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author maldad
 */
public class Polinomio extends javax.swing.JPanel {

    /**
     * Creates new form Polinomio
     */
    private int terminos;
    public Polinomio() {
        initComponents();
        terminos = 2;
        campoTextoNumero3.setVisible(false);
        campoTextoNumero4.setVisible(false);
        campoTextoNumero3.setText("0.00");
        campoTextoNumero4.setText("0.00");
        jLabel2.setVisible(false);
        jLabel1.setVisible(false);
    }
    
    public void setTerminos(int n){
        if(n == 2){
            terminos = n;
            campoTextoNumero3.setVisible(false);
            jLabel2.setVisible(false);
            campoTextoNumero4.setVisible(false);
            jLabel1.setVisible(false);
        }
        if(n == 3){
            terminos = n;
            campoTextoNumero3.setVisible(true);
            jLabel2.setVisible(true);
        }
        if(n == 4){
            terminos = n;
            campoTextoNumero3.setVisible(true);
            jLabel2.setVisible(true);
            campoTextoNumero4.setVisible(true);
            jLabel1.setVisible(true);
        }
    }
    
    public float evaluar(){
        float v1 = Float.parseFloat(campoTextoNumero1.getText());
        float v2 = Float.parseFloat(campoTextoNumero2.getText());
        float v3 = Float.parseFloat(campoTextoNumero3.getText());
        float v4 = Float.parseFloat(campoTextoNumero4.getText());
        float equis = Float.parseFloat(campoTextoNumero5.getText());
        
        return (float)(v1 + (equis * v2) + 
                (Math.pow(equis, 2) * v3) + (Math.pow(equis, 3) * v4));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoTextoNumero1 = new CampoTextoNumero();
        campoTextoNumero2 = new CampoTextoNumero();
        campoTextoNumero3 = new CampoTextoNumero();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoTextoNumero4 = new CampoTextoNumero();
        jButton1 = new javax.swing.JButton();
        campoTextoNumero5 = new CampoTextoNumero();
        jLabel4 = new javax.swing.JLabel();

        campoTextoNumero1.setLimMin(0);

        campoTextoNumero2.setLimMin(0);

        campoTextoNumero3.setLimMin(0);

        jLabel1.setText("x^3 +");

        jLabel2.setText("x^2 +");

        jLabel3.setText("x +");

        campoTextoNumero4.setLimMin(0);
        campoTextoNumero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoNumero4ActionPerformed(evt);
            }
        });

        jButton1.setText("evaluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        campoTextoNumero5.setLimMax(50);
        campoTextoNumero5.setLimMin(0);

        jLabel4.setText("x = ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoTextoNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addComponent(campoTextoNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoTextoNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoTextoNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoTextoNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(campoTextoNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel4))
                .addContainerGap(121, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoTextoNumero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoNumero4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoNumero4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println(evaluar());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CampoTextoNumero campoTextoNumero1;
    private CampoTextoNumero campoTextoNumero2;
    private CampoTextoNumero campoTextoNumero3;
    private CampoTextoNumero campoTextoNumero4;
    private CampoTextoNumero campoTextoNumero5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
